type Category {

    categoryId: Int!

    categoryName: String

    icon: String

    status: Int!
}


type Product {

    productId: Int!

    productName: String!

    description: String

    price: Float!

    image: String

    createdAt: String

    category: Category
}


type ProductPage {

    content: [Product!]!

    page: Int!

    size: Int!

    totalElements: Int!

    totalPages: Int!

    first: Boolean!

    last: Boolean!
}


type CategoryPage {

    content: [Category!]!

    page: Int!

    size: Int!

    totalElements: Int!

    totalPages: Int!

    first: Boolean!

    last: Boolean!
}


input CategoryInput {

    categoryName: String!

    icon: String

    status: Int
}


input ProductInput {

    productName: String!

    description: String

    price: Float!

    image: String

    categoryId: Int!
}


type Query {

    hello: String!

    productsByPriceAsc: [Product!]!

    productsByCategory(
        categoryId: Int!
    ): [Product!]!

    categories: [Category!]!

    productById(
        id: Int!
    ): Product

    categoryById(
        id: Int!
    ): Category

    productPage(
        keyword: String
        page: Int
        size: Int
    ): ProductPage!

    categoryPage(
        keyword: String
        page: Int
        size: Int
    ): CategoryPage!
}


type Mutation {

    createCategory(
        input: CategoryInput!
    ): Category!

    updateCategory(
        id: Int!
        input: CategoryInput!
    ): Category

    deleteCategory(
        id: Int!
    ): Boolean!


    createProduct(
        input: ProductInput!
    ): Product!

    updateProduct(
        id: Int!
        input: ProductInput!
    ): Product

    deleteProduct(
        id: Int!
    ): Boolean!
}